before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs

lint:
  script:
    - npm run dev

build:
  script:
    - npm run dev

test:
  script:
    - npm run dev

deploy:
  script:
    - npm run dev
