image: "ubuntu:18.04"

before_script:
    - docker system prune --volumes -af 

stages:
    - pre-test
    - test
    - post-test

build_image:
  stage: pre-test
  script:
    - echo "WOO"
  tags:
    - full-stack
