image: "ubuntu:18.04"

before_script:
  - export HOME=/home/gitlab-runner/
  - chmod +x ./setup_env.sh
  - ./setup_env.sh

after_script:
    - docker-compose down
    - docker system prune --volumes -af

stages:
    - build
    - test
    - deploy

pylint:
  stage: test
  script:
    - docker-compose -f docker-compose.yml -f compose/docker-compose.dev.yml up -d --build django-server
    - make dtest-pylint
  tags:
    - full-stack

django:
  stage: test
  script:
    - docker-compose -f docker-compose.yml -f compose/docker-compose.dev.yml up -d --build django-server postgres-server
    - ./scripts/wait_till_container_healthy.sh drumrose_django-server_1
    - make dtest-django
  tags:
    - full-stack

lintjs:
  stage: test
  script:
    - docker-compose -f docker-compose.yml -f compose/docker-compose.dev.yml up -d --build nuxt-server
    - ./scripts/wait_till_container_healthy.sh drumrose_nuxt-server_1
    - make dtest-lint
  tags:
    - full-stack
