image: "ubuntu:18.04"

after_script:
    - docker-compose down
    - docker system prune --volumes -af

stages:
    - build
    - test
    - deploy

pylint:
  stage: test
  script:
    - docker-compose up -d --build tests-server
    - make dtest-pylint
  tags:
    - full-stack

django:
  stage: test
  script:
    - docker-compose up -d --build django-server postgres-server
    - ./scripts/wait_till_container_healthy.sh drumrose_django-server_1
    - make dtest-django
  tags:
    - full-stack

lintjs:
  stage: test
  script:
    - docker-compose up -d --build nuxt-server
    - make dtest-lint
  tags:
    - full-stack
