image: "ubuntu:18.04"

after_script:
    - docker-compose down
    - docker system prune --volumes -af

stages:
    - pre-test
    - test
    - post-test

pylint:
  stage: pre-test
  script:
    - docker-compose build tests-server
    - docker-compose up -d tests-server
    - make dtest-pylint
  tags:
    - full-stack
