image: "ubuntu:18.04"

before_script:
    - docker system prune --volumes -af
    - ./scripts/continuous_integration/gitlab_runner_setup.sh

stages:
    - pre-test
    - test
    - post-test

pylint:
  stage: pre-test
  script:
    - make up
  tags:
    - full-stack
