version: "3.3"
services:
  nuxt:
    build: services/neptune-nuxt
    ports:
    - "3000:3000"
    command: "npm run dev"

  django:
    build: services/neptune-django
    ports:
    - "8000:8000"
    command: "tail -f /dev/null"

  apple-music-communicator:
    build: services/apple-music-communicator
