version: "3.3"
services:
  nginx-server:
    image: registry.gitlab.com/jbrill/drumrose/nginx-server:dev
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 443:443
      - 80:80
    env_file:
      - ./.nginx.env
    depends_on:
      - django-server
    environment:
      - DRUMROSE_DOMAIN=drumrose.com

  django-server:
    image: registry.gitlab.com/jbrill/drumrose/django-server:dev
    ports:
    - "8000:8000"
    env_file:
      - ./.django.env
    healthcheck:
      test: "curl -sS http://localhost:8000 || exit 1"
      interval: "60s"
      timeout: "3s"
      retries: 3

  nuxt-server:
    image: registry.gitlab.com/jbrill/drumrose/nuxt-server:dev
    ports:
      - 3001:3001
    env_file:
      - ./.nuxt.env
    depends_on:
      - django-server
    healthcheck:
      test: "curl -sS http://localhost:3001/healthcheck || exit 1"
      interval: "60s"
      timeout: "3s"
      retries: 3