version: "3.3"
services:
  nuxt:
    build: services/nuxt
    ports:
    - "3000:3000"
    command: "npm run dev"

  django:
    build: services/django
    ports:
    - "8000:8000"
    command: "python3 neptuneapi/manage.py runserver"

  postgres:
    build: services/postgres
    ports:
    - "5464:5453"
