version: "3.3"
services:
  nuxt:
    build: services/nuxt
    ports:
    - "3000:3000"
    command: "npm run dev"

  django:
    build: services/django
    ports:
    - "8000:8000"
    environment:
      POSTGRES_DB_NAME: drumrose_db
      POSTGRES_USER: drumrose_user
      POSTGRES_PASSWORD: drumrose_password
      POSTGRES_HOST: postgres-server
      POSTGRES_PORT: 5432
    command: "python3 manage.py runserver"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB_NAME: drumrose_db
      POSTGRES_USER: drumrose_user
      POSTGRES_PASSWORD: drumrose_password
      POSTGRES_HOST: postgres-server
      POSTGRES_PORT: 5432
