version: "3.3"
services:
  nginx-server:
    image: nginx:latest
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 443:443
      - 80:80

  nuxt-server:
    build: services/nuxt
    ports:
    - "3000:3000"
    command: "npm run dev"

  django-server:
    build: services/django
    ports:
    - "8000:8000"
    environment:
      POSTGRES_DB_NAME: drumrose_db
      POSTGRES_USER: drumrose_user
      POSTGRES_PASSWORD: drumrose_password
      POSTGRES_HOST: postgres-server
      POSTGRES_PORT: 5432
    command: "python3 manage.py runserver 0.0.0.0:8000"

  postgres-server:
    build: services/postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB_NAME: drumrose_db
      POSTGRES_USER: drumrose_user
      POSTGRES_PASSWORD: drumrose_password
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    volumes:
      - /var/lib/postgresql/:/var/lib/postgresql/
