version: "3.3"
services:
  django-server:
    volumes:
    - '/root/drumrose/services/django:/usr/local/drumrose/services/django'
    environment:
      DEBUG: 'true'
  
  nuxt-server:
    volumes:
    - '/root/drumrose/services/nuxt/components:/usr/local/drumrose/services/nuxt/components'
    environment:
      DEBUG: 'true'
  
  tests-server:
    volumes:
    - '/root/drumrose:/usr/local/drumrose'
