version: "3.7"
services:
    nuxt:
        build: services/neptune-nuxt

    django:
        build: services/neptune-django

    apple-music-communicator:
        build: services/apple-music-communicator
