version: "3.3"
services:
  django-server:
    volumes:
    - './services/django/api/:/usr/local/drumrose/api/'
    environment:
      DEBUG: 1
    env_file:
      - './.django.env'
    build: ./services/django
    restart: always

  nuxt-server:
    volumes:
    - './services/nuxt/src/:/usr/local/drumrose/src/'
    - './services/nuxt/nuxt.config.js:/usr/local/drumrose/nuxt.config.js'
    environment:
      DEBUG: 1
      NODE_ENV: 'development'
    env_file:
      - './.nuxt.env'
    build: ./services/nuxt

  nginx-server:
    environment:
      DRUMROSE_DOMAIN: 'teton.drumrose.io'
      NUXT_PORT: 3000
    env_file:
      - './.nginx.env'
    build: ./services/nginx