version: "3.3"
services:
  nginx-server:
    image: nginx:latest
    volumes:
      - ./services/nginx:/etc/nginx
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 443:443
      - 80:80

  nuxt-server:
    build: services/nuxt
    ports:
    - "3000:3000"
    env_file:
    - ".nuxt.env"
    healthcheck:
      test: "curl -sS http://localhost:3000/healtcheck || exit 1"
      interval: "60s"
      timeout: "3s"
      retries: 3
    command: "npm run dev"

  django-server:
    build: 
      context: .
      dockerfile: services/django/Dockerfile
    ports:
    - "8000:8000"
    env_file:
      - .django.env
    healthcheck:
      test: "curl -sS http://django-server:8000 || exit 1"
      interval: "60s"
      timeout: "3s"
      retries: 3
    depends_on:
    - postgres-server
    command: ./django_entry.sh

  postgres-server:
    build: services/postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB_NAME: drumrose_db
      POSTGRES_USER: drumrose_user
      POSTGRES_PASSWORD: drumrose_password
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U drumrose_user"]
      interval: 3s
      timeout: 30s
      retries: 3
    volumes:
      - /var/lib/postgresql/:/var/lib/postgresql/
  
  tests-server:
    build:
      context: .
      dockerfile: tests/Dockerfile
    command: "tail -f /dev/null"
