# Generated by Django 2.1.2 on 2020-06-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="album", name="artwork_url",),
        migrations.RemoveField(model_name="album", name="name",),
        migrations.RemoveField(model_name="artist", name="artist_photo_url",),
        migrations.RemoveField(model_name="artist", name="name",),
        migrations.RemoveField(model_name="song", name="album",),
        migrations.RemoveField(model_name="song", name="artist",),
        migrations.RemoveField(model_name="song", name="name",),
        migrations.AddField(
            model_name="artist",
            name="apple_music_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, unique=True
            ),
        ),
    ]
