# Generated by Django 2.1.2 on 2020-04-13 18:16

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="album", name="artists",),
        migrations.RemoveField(model_name="song", name="albums",),
        migrations.RemoveField(model_name="user", name="posts",),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.User",
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.Album",
            ),
        ),
    ]
