# Generated by Django 2.1.2 on 2020-08-05 00:58

import uuid

import django.db.models.deletion

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlbumReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("review", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlaylistReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("review", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrackReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("review", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="page_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="page_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="page_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="page_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="trackreview",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.Song"
            ),
        ),
        migrations.AddField(
            model_name="trackreview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.UserProfile",
            ),
        ),
        migrations.AddField(
            model_name="playlistreview",
            name="playlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.Playlist"
            ),
        ),
        migrations.AddField(
            model_name="playlistreview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.UserProfile",
            ),
        ),
        migrations.AddField(
            model_name="albumreview",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.Album"
            ),
        ),
        migrations.AddField(
            model_name="albumreview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.UserProfile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trackreview", unique_together={("user", "track")},
        ),
        migrations.AlterUniqueTogether(
            name="playlistreview", unique_together={("user", "playlist")},
        ),
        migrations.AlterUniqueTogether(
            name="albumreview", unique_together={("user", "album")},
        ),
    ]
