# Generated by Django 3.1 on 2020-08-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0002_auto_20200805_0058")]

    operations = [
        migrations.AddField(
            model_name="song",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
