# Generated by Django 2.1.2 on 2020-04-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20200413_1816"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="artist_photo_url",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
