# Generated by Django 2.1.2 on 2020-06-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20200622_2230"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritedalbum",
            name="auth0_user_id",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="favoritedplaylist",
            name="auth0_user_id",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="favoritedtrack",
            name="auth0_user_id",
            field=models.CharField(max_length=200),
        ),
    ]
