# Generated by Django 2.1.2 on 2020-06-25 00:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20200622_2301"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auth0ManagementToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_authorized", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
    ]
