# Generated by Django 3.1 on 2020-09-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0003_song_name")]

    operations = [
        migrations.AddField(
            model_name="albumreview",
            name="rating",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playlistreview",
            name="rating",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackreview",
            name="rating",
            field=models.TextField(blank=True, null=True),
        ),
    ]
