# Generated by Django 2.1.2 on 2020-04-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_song_artist_photo_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="song", name="artist_photo_url",),
        migrations.AddField(
            model_name="artist",
            name="artist_photo_url",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
