# Generated by Django 2.1.2 on 2020-04-15 02:38

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20200415_0237"),
    ]

    operations = [
        migrations.RemoveField(model_name="song", name="artists",),
        migrations.AddField(
            model_name="song",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.Artist",
            ),
        ),
    ]
