# Generated by Django 2.1.2 on 2020-04-09 17:57

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20200408_1741"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="album",
            field=models.ManyToManyField(to="api.Album"),
        ),
        migrations.AddField(
            model_name="song",
            name="artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.Artist",
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="songs",
            field=models.ManyToManyField(
                related_name="_album_songs_+", to="api.Song"
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="songs",
            field=models.ManyToManyField(
                blank=True, related_name="_artist_songs_+", to="api.Song"
            ),
        ),
    ]
