# Generated by Django 2.1.2 on 2020-06-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20200625_2221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auth0managementtoken",
            name="access_token",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
