# Generated by Django 2.1.2 on 2020-04-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20200415_0238"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="apple_music_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
