# Generated by Django 2.1.2 on 2020-04-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20200409_1757"),
    ]

    operations = [
        migrations.RemoveField(model_name="album", name="songs",),
        migrations.RemoveField(model_name="artist", name="albums",),
        migrations.RemoveField(model_name="artist", name="songs",),
        migrations.RemoveField(model_name="song", name="artist",),
        migrations.AddField(
            model_name="song",
            name="artists",
            field=models.ManyToManyField(
                related_name="songs",
                related_query_name="song",
                to="api.Artist",
            ),
        ),
        migrations.RemoveField(model_name="album", name="artists",),
        migrations.AddField(
            model_name="album",
            name="artists",
            field=models.ManyToManyField(
                related_name="albums",
                related_query_name="album",
                to="api.Artist",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="album",
            field=models.ManyToManyField(
                related_name="songs", related_query_name="song", to="api.Album"
            ),
        ),
    ]
