# Generated by Django 2.1.2 on 2020-04-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20200409_1809"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="user",),
        migrations.RemoveField(model_name="user", name="posts",),
        migrations.AddField(
            model_name="user",
            name="posts",
            field=models.ManyToManyField(
                null=True,
                related_name="users",
                related_query_name="user",
                to="api.Post",
            ),
        ),
    ]
