# Generated by Django 2.1.2 on 2020-06-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20200625_2223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auth0managementtoken",
            name="access_token",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
