# Generated by Django 3.1.1 on 2021-01-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0006_auto_20210117_1944")]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="tracks",
            field=models.ManyToManyField(blank=True, to="api.Song"),
        )
    ]
