# Generated by Django 3.1.1 on 2021-01-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0007_auto_20210117_1944")]

    operations = [
        migrations.AlterField(
            model_name="albumreview",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="playlistreview",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trackreview",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
