# Generated by Django 2.1.2 on 2020-04-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20200409_1810"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song", old_name="album", new_name="albums",
        ),
        migrations.AlterField(
            model_name="user",
            name="posts",
            field=models.ManyToManyField(
                related_name="users", related_query_name="user", to="api.Post"
            ),
        ),
    ]
