# Generated by Django 2.1.2 on 2020-05-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_playlist"),
    ]

    operations = [
        migrations.RemoveField(model_name="playlist", name="song",),
        migrations.AddField(
            model_name="playlist",
            name="song",
            field=models.ManyToManyField(to="api.Song"),
        ),
    ]
