# Generated by Django 2.1.2 on 2020-06-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20200625_2224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auth0managementtoken",
            name="access_token",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
