# Generated by Django 3.2.7 on 2022-02-03 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0008_auto_20210118_1538")]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="followers"),
        migrations.AddField(
            model_name="userprofile",
            name="followers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.userprofile",
            ),
        ),
    ]
