# Generated by Django 2.1.2 on 2018-11-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181109_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='apple_music_id',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
