# Generated by Django 2.1.2 on 2020-05-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_auto_20200512_2315"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlist", old_name="song", new_name="tracks",
        ),
    ]
