# Generated by Django 2.1.2 on 2020-05-14 18:49

import uuid

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_auto_20200512_2315"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoritedAlbum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.Album",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoritedPlaylist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.Playlist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoritedTrack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.Song",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.User",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="post", name="song",),
        migrations.RemoveField(model_name="post", name="user",),
        migrations.DeleteModel(name="Post",),
        migrations.AlterUniqueTogether(
            name="favoritedtrack", unique_together={("user", "song")},
        ),
        migrations.AlterUniqueTogether(
            name="favoritedplaylist", unique_together={("user", "playlist")},
        ),
        migrations.AlterUniqueTogether(
            name="favoritedalbum", unique_together={("user", "album")},
        ),
    ]
