# Generated by Django 3.2.7 on 2022-02-03 16:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [("api", "0009_auto_20220203_1609")]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="followers"),
        migrations.CreateModel(
            name="FollowContain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "follower_user_id",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="api.userprofile",
                    ),
                ),
                (
                    "following_user_id",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="api.userprofile",
                    ),
                ),
            ],
            options={"unique_together": {("follower_user_id", "following_user_id")}},
        ),
    ]
