# Generated by Django 2.1.2 on 2018-12-10 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181125_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='name',
        ),
    ]
