# Generated by Django 2.1.2 on 2020-05-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_auto_20200514_1849"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="apple_music_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="apple_music_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, unique=True
            ),
        ),
    ]
