# Generated by Django 2.1.2 on 2020-06-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_auto_20200527_0145"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="apple_music_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, unique=True
            ),
        ),
    ]
