# Generated by Django 2.1.2 on 2020-06-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_playlist_apple_music_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_authorized_apple_music_user",
            field=models.BooleanField(default=False),
        ),
    ]
