# Drumrose Front-end
# Version: 1.0
FROM ubuntu:18.04
LABEL Maintainer="Jason Brill <jason@drumrose.com>"

# Install Python and Package Libraries
RUN apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean
RUN apt-get install -y \
    curl \
    sudo \
    vim \
    nodejs \
    npm

RUN curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -

RUN sudo apt-get install -y nodejs

RUN mkdir -p /usr/local/drumrose/

COPY . /usr/local/drumrose/

WORKDIR /usr/local/drumrose/

EXPOSE 3001

ARG DOMAIN_HOST
ENV DOMAIN_HOST ${DOMAIN_HOST}

ARG AUTH0_DOMAIN
ENV AUTH0_DOMAIN ${AUTH0_DOMAIN}

ARG AUTH0_CLIENT_ID
ENV AUTH0_CLIENT_ID ${AUTH0_CLIENT_ID}

ARG API_URL
ENV API_URL ${API_URL}

ARG API_AUDIENCE
ENV API_AUDIENCE ${API_AUDIENCE}

ARG NODE_ENV
ENV NODE_ENV production

# CI=1 to not ignore tty output
RUN CI=1 npm install

RUN npm run build

CMD ["npm", "run", "start"]
