version: "3.3"
services:
  django-server:
    volumes:
    - '${HOME}/drumrose/services/django:/usr/local/drumrose/services/django'
    environment:
      DEBUG: 1
  
  nuxt-server:
    volumes:
    - '${HOME}/drumrose/services/nuxt/src:/usr/local/drumrose/services/nuxt/src'
    - '${HOME}/drumrose/services/nuxt/nuxt.config.js:/usr/local/drumrose/services/nuxt/nuxt.config.js'
    environment:
      DEBUG: 1
