version: "3.3"
services:
  nginx-server:
    image: nginx:latest
    volumes:
      - ./services/nginx:/etc/nginx
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 443:443
      - 80:80

  nuxt-server:
    entrypoint: ["echo", "Service nuxt disabled"]

  django-server:
    build: 
      context: .
      dockerfile: services/django/Dockerfile
    ports:
    - "8000:8000"
    env_file:
      - .django.prod.env
    healthcheck:
      test: "curl -sS http://django-server:8000 || exit 1"
      interval: "60s"
      timeout: "3s"
      retries: 3
    depends_on:
    - postgres-server
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000

  tests-server:
    entrypoint: ["echo", "Service tests disabled"]

