# Generated by Django 2.1.2 on 2018-10-21 23:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neptuneapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neptunealbum',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neptunealbum',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='neptunealbum',
            name='songs',
            field=models.ManyToManyField(to='neptuneapi.NeptuneSong'),
        ),
        migrations.AddField(
            model_name='neptuneartist',
            name='albums',
            field=models.ManyToManyField(to='neptuneapi.NeptuneAlbum'),
        ),
        migrations.AddField(
            model_name='neptuneartist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neptuneartist',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='neptuneartist',
            name='songs',
            field=models.ManyToManyField(to='neptuneapi.NeptuneSong'),
        ),
        migrations.AddField(
            model_name='neptunepost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neptunepost',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='neptunepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neptuneapi.NeptuneUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neptunesong',
            name='albums',
            field=models.ManyToManyField(to='neptuneapi.NeptuneAlbum'),
        ),
        migrations.AddField(
            model_name='neptunesong',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neptunesong',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='neptuneuser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neptuneuser',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='neptuneuser',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neptuneapi.NeptunePost'),
            preserve_default=False,
        ),
    ]
