# Generated by Django 2.1.2 on 2018-10-23 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neptuneapi', '0002_auto_20181021_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='neptunealbum',
            name='artists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neptuneapi.NeptuneArtist'),
            preserve_default=False,
        ),
    ]
