# Generated by Django 2.1.2 on 2018-10-23 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neptuneapi', '0005_auto_20181023_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='neptunesong',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neptuneapi.NeptuneArtist'),
            preserve_default=False,
        ),
    ]
